Repository openedx/frontend-app-learning, pull requests merged in 2021-12, with the labels that each got.

#715 asadiqbal08/Removed course header from Learning MFE
  package-lock.json
  package.json
  src/course-header/AnonymousUserMenu.jsx
  src/course-header/AuthenticatedUserDropdown.jsx
  src/course-header/Header.jsx
  src/course-header/Header.test.jsx
  src/course-header/messages.js
  src/course-home/goal-unsubscribe/GoalUnsubscribe.jsx
  src/course-tabs/CourseTabsNavigation.jsx
  src/course-tabs/CourseTabsNavigation.test.jsx
  src/course-tabs/index.js
  src/course-tabs/messages.js
  src/courseware/CoursewareContainer.test.jsx
  src/generic/messages.js
  src/index.scss
  src/tab-page/LoadedTabPage.jsx
  src/tab-page/LoadedTabPage.test.jsx
  src/tab-page/TabPage.jsx
Labels: open-source-contribution, changes requested

#780 fix: Use Link from router to fix path based routing issue
  src/courseware/course/CourseBreadcrumbs.jsx
  src/courseware/course/CourseBreadcrumbs.test.jsx
Labels: open-source-contribution, waiting on author, core committer

#777 fix: Use Link from router to fix path based routing issue
  src/courseware/course/CourseBreadcrumbs.jsx
  src/courseware/course/CourseBreadcrumbs.test.jsx
Labels: needs triage, open-source-contribution
