Repository openedx/frontend-app-learning, pull requests merged in 2023-07, with the labels that each got.

#983 fix: save scroll position on exit from video xblock fullscreen mode
  src/courseware/course/sequence/Unit.jsx
  src/courseware/course/sequence/Unit.test.jsx
Labels: open-source-contribution, product review, waiting on author

#1136 [BD-46] feat: added Paragon translations
  src/i18n/index.js
Labels: blended

#1145 feat: include paragon in atlas pull
  Makefile
Labels: open-source-contribution

#1094 fix: make iframe wrapper take all vieport width
  src/index.scss
Labels: open-source-contribution, product review, waiting for eng review
