Repository openedx/frontend-app-learning, pull requests merged in 2023-05, with the labels that each got.

#1102 [FC-0014] update frontend-platform version to v4.2.0
  package-lock.json
  package.json
Labels: open-source-contribution, waiting on author

#1105 [FC-0014][palm] update frontend-platform version to v4.2.0
  package-lock.json
  package.json
Labels: open-source-contribution, waiting on author

#1052 fix: show date on home page
  src/alerts/course-start-alert/CourseStartAlert.jsx
Labels: open-source-contribution, product review

#1106 [FC-0014][olive] update frontend-platform version to v4.2.0
  package-lock.json
  package.json
Labels: open-source-contribution, blocked by other work

#1120 fix: sync LMS_BASE_URL for bookmark API if changed
  src/courseware/course/bookmark/BookmarkButton.test.jsx
  src/courseware/course/bookmark/data/api.js
Labels: open-source-contribution, core contributor
