Repository openedx/frontend-app-learning, pull requests merged in 2023-01, with the labels that each got.

#1041 fix: text in goal modal
  src/courseware/course/celebration/WeeklyGoalCelebrationModal.jsx
Labels: open-source-contribution

#975 fix: fix alignment in the streak celebration modal
  src/shared/streak-celebration/StreakCelebrationModal.jsx
  src/shared/streak-celebration/StreakCelebrationModal.scss
Labels: open-source-contribution, product review

#987 Automate Browserlist DB Update
  .github/workflows/update-browserslist-db.yml
Labels: engineering review
