Repository openedx/frontend-app-learning, pull requests merged in 2024-09, with the labels that each got.

#1456 Clean up dependencies
  package-lock.json
  package.json
  src/index.jsx
  src/setupTest.js
Labels: open-source-contribution

#1473 fix: sass deprecation warning in GradeBar.scss
  src/course-home/progress-tab/grades/course-grade/GradeBar.scss
Labels: open-source-contribution

#1479 Use BundleWatch to monitor bundle size
  Makefile
  package-lock.json
  package.json
Labels: open-source-contribution

#1472 Update README to explain how to run this using Tutor
  .env
  .env.development
  .env.test
  README.rst
  package.json
Labels: open-source-contribution

#1476 fix: upload codecov report as a separate workflow step
  .github/workflows/validate.yml
Labels: open-source-contribution, core contributor

#1427 feat: support jumping to specific xblock id
  src/courseware/course/sequence/Unit/index.jsx
  src/courseware/course/sequence/Unit/index.test.jsx
  src/courseware/course/sequence/Unit/urls.js
  src/courseware/course/sequence/Unit/urls.test.js
Labels: open-source-contribution, core contributor

#1434 fix: masquerade dropdown not showing current selection
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.test.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidgetOption.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidgetOption.test.jsx
Labels: open-source-contribution

#1397 fix: increase subsection grades rounding precision
  src/course-home/data/__snapshots__/redux.test.js.snap
  src/course-home/data/api.js
Labels: open-source-contribution, product review, core contributor, product review complete

#1429 fix: corrects the navigation issue if the student does not pass the entrance exam
  src/course-home/progress-tab/certificate-status/CertificateStatus.jsx
  src/courseware/course/course-exit/utils.js
  src/courseware/course/sequence/sequence-navigation/UnitNavigation.test.jsx
  src/courseware/course/sequence/sequence-navigation/hooks.js
Labels: open-source-contribution, waiting on author
