Repository openedx/frontend-app-learning, pull requests merged in 2024-08, with the labels that each got.

#1430 docs: transfer maintainership from 2U Aurora to volunteers (Braden + Farhaan)
  catalog-info.yaml
Labels: open-source-contribution, core contributor

#1404 fix: iframe height for discussions sidebar
  src/courseware/course/sidebar/sidebars/discussions/Discussions.scss
  src/courseware/course/sidebar/sidebars/discussions/DiscussionsSidebar.jsx
  src/index.scss
Labels: open-source-contribution, waiting for eng review, backport

#1392 fix: iframe height for discussions sidebar
  src/courseware/course/sidebar/sidebars/discussions/Discussions.scss
  src/courseware/course/sidebar/sidebars/discussions/DiscussionsSidebar.jsx
  src/index.scss
Labels: open-source-contribution, waiting for eng review, backport

#1391 feat: updated frontend-build & frontend-platform major versions
  jest.config.js
  package-lock.json
  package.json
  src/course-home/courseware-search/__snapshots__/map-search-response.test.js.snap
  src/course-home/data/__snapshots__/redux.test.js.snap
  src/courseware/course/Course.test.jsx
  src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.test.jsx
  src/courseware/course/sequence/Sequence.test.jsx
  src/courseware/course/sidebar/sidebars/notifications/NotificationTray.test.jsx
Labels: maintenance
