Repository openedx/frontend-app-learning, pull requests merged in 2024-10, with the labels that each got.

#1491 fix: send XBlock visibility status to the LMS
  package-lock.json
  package.json
  src/courseware/course/sequence/Unit/hooks/useIFrameBehavior.js
  src/courseware/course/sequence/Unit/hooks/useIFrameBehavior.test.js
Labels: open-source-contribution

#1490 chore(deps): bump sass to v1.79 and sass-loader to v16
  package-lock.json
  package.json
Labels: open-source-contribution, core contributor, waiting for eng review

#1502 feat(deps): update header to 5.6.0
  package-lock.json
  package.json
Labels: create-sandbox

#1505 fix: Untranslatable strings in Instructor Toolbar #1193 #1449
  src/instructor-toolbar/InstructorToolbar.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx
  src/instructor-toolbar/masquerade-widget/messages.ts
  src/instructor-toolbar/messages.ts
Labels: open-source-contribution

#1380 feat: option to show/hide ungraded assignment in progress page
  .env
  .env.development
  .env.test
  src/course-home/progress-tab/ProgressTab.test.jsx
  src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
  src/course-home/progress-tab/grades/detailed-grades/DetailedGradesTable.jsx
  src/course-home/progress-tab/grades/detailed-grades/ProblemScoreDrawer.jsx
  src/course-home/progress-tab/grades/messages.ts
  src/course-home/progress-tab/utils.ts
  src/index.jsx
Labels: open-source-contribution, product review, core contributor, waiting for eng review, product review complete
