Repository openedx/frontend-app-learning, pull requests merged in 2024-12, with the labels that each got.

#1513 Convert masquerade UI widgets to Function Components + TypeScript
  package-lock.json
  package.json
  src/course-home/dates-tab/DatesTab.test.jsx
  src/course-home/outline-tab/OutlineTab.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTrigger.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSection.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSequence.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarUnit.test.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeUserNameInput.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeUserNameInput.tsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.test.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.test.tsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidget.tsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidgetOption.jsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidgetOption.test.tsx
  src/instructor-toolbar/masquerade-widget/MasqueradeWidgetOption.tsx
  src/instructor-toolbar/masquerade-widget/data/api.js
  src/instructor-toolbar/masquerade-widget/data/api.ts
  src/instructor-toolbar/masquerade-widget/index.js
  src/instructor-toolbar/masquerade-widget/index.ts
Labels: open-source-contribution, core contributor, waiting for eng review

#1547 Revert "fix: add test in CourseOutlineTray" and "fix: only one in-course experience sidebar can be open at a time failing"
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.jsx
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSequence.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSequence.test.jsx
Labels: open-source-contribution

#1552 fix: update iframe feature policy
  src/courseware/course/sequence/Unit/ContentIFrame.jsx
Labels: open-source-contribution, waiting on author
