Repository openedx/frontend-app-learning, pull requests merged in 2024-11, with the labels that each got.

#1500 fix: corrects typo in IFRAME_FEATURE_POLICY
  src/courseware/course/sequence/Unit/ContentIFrame.jsx
Labels: open-source-contribution

#1525 feat: update to header with new FPF `pluginProps`
  package-lock.json
  package.json
Labels: create-sandbox

#1436 feat: hide studio button for limited staff [BB-9082]
  src/course-home/data/pact-tests/lmsPact.test.jsx
  src/instructor-toolbar/InstructorToolbar.jsx
  src/tab-page/LoadedTabPage.jsx
Labels: open-source-contribution, product review, waiting for eng review, product review complete
