Repository openedx/frontend-app-learning, pull requests merged in 2024-03, with the labels that each got.

#1264 docs: broken readme fixed
  README.rst
Labels: open-source-contribution, waiting for eng review

#1262 feat: show message in course outline when hide from toc is enabled
  src/course-home/data/__snapshots__/redux.test.js.snap
  src/course-home/data/api.js
  src/course-home/outline-tab/OutlineTab.test.jsx
  src/course-home/outline-tab/Section.jsx
  src/course-home/outline-tab/SequenceLink.jsx
  src/course-home/outline-tab/messages.js
  webpack.dev-tutor.config.js
Labels: open-source-contribution, blocked by other work, product review, create-sandbox

#1273 feat: use navigation sequence metadata to disable navigation components
  src/course-home/data/__snapshots__/redux.test.js.snap
  src/course-home/data/api.js
  src/courseware/course/Course.jsx
  src/courseware/course/Course.test.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigation.test.jsx
  src/courseware/course/sequence/sequence-navigation/hooks.js
  src/courseware/data/api.js
Labels: open-source-contribution, blocked by other work, product review, waiting on author, core contributor, create-sandbox

#1288 Fix RTL for Handouts
  src/course-home/outline-tab/LmsHtmlFragment.jsx
Labels: open-source-contribution, waiting for eng review, backport

#1223 fix: wrong text-color class and text contrast on dates page
  src/course-home/dates-tab/timeline/badgelist.jsx
Labels: open-source-contribution, waiting for eng review

#1220 fix: RTL for the upgrade notification list
  src/generic/upgrade-notification/UpgradeNotification.scss
Labels: open-source-contribution, waiting for eng review

#1289 fix: correct rtl for handouts
  src/course-home/outline-tab/LmsHtmlFragment.jsx
Labels: open-source-contribution, waiting for eng review

#1219 fix: container width and responsive for navigation block
  src/courseware/course/sequence/Sequence.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
  src/courseware/course/sidebar/SidebarTriggers.jsx
  src/courseware/course/sidebar/common/TriggerBase.jsx
  src/generic/tabs/useIndexOfLastVisibleChild.js
  src/index.scss
Labels: open-source-contribution, waiting for eng review

#1227 fix: container width and responsive for navigation block
  src/courseware/course/sequence/Sequence.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
  src/courseware/course/sidebar/SidebarTriggers.jsx
  src/courseware/course/sidebar/common/TriggerBase.jsx
  src/generic/tabs/useIndexOfLastVisibleChild.js
  src/index.scss
Labels: open-source-contribution, waiting for eng review, backport

#1218 fix: container width and responsive for navigation block
  src/courseware/course/sequence/Sequence.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigation.jsx
  src/courseware/course/sidebar/SidebarTriggers.jsx
  src/courseware/course/sidebar/common/TriggerBase.jsx
  src/generic/tabs/useIndexOfLastVisibleChild.js
  src/index.scss
Labels: open-source-contribution, backport

#1198 feat!: remove Transifex calls for OEP-58 | FC-0012
  .gitignore
  .tx/config
  Makefile
  src/i18n/index.js
  src/i18n/messages/ar.json
  src/i18n/messages/de.json
  src/i18n/messages/de_DE.json
  src/i18n/messages/es_419.json
  src/i18n/messages/fa_IR.json
  src/i18n/messages/fr.json
  src/i18n/messages/fr_CA.json
  src/i18n/messages/hi.json
  src/i18n/messages/it.json
  src/i18n/messages/it_IT.json
  src/i18n/messages/pt.json
  src/i18n/messages/pt_PT.json
  src/i18n/messages/ru.json
  src/i18n/messages/uk.json
  src/i18n/messages/zh_CN.json
Labels: open-source-contribution

#1222 fix: wrong text-color class and text contrast on dates page
  src/course-home/dates-tab/timeline/badgelist.jsx
Labels: open-source-contribution, waiting for eng review, backport

#1229 fix: wrong text-color class and text contrast on dates page
  src/course-home/dates-tab/timeline/badgelist.jsx
Labels: open-source-contribution, waiting for eng review, backport

#1204 fix: course update iframe
  src/course-home/outline-tab/LmsHtmlFragment.jsx
  src/course-home/outline-tab/OutlineTab.test.jsx
  src/course-home/outline-tab/widgets/WelcomeMessage.jsx
Labels: open-source-contribution, waiting for eng review
