Repository openedx/frontend-app-learning, pull requests merged in 2025-01, with the labels that each got.

#1572 Bump paragon to v22.13.0, fix minor TypeScript warning
  package-lock.json
  package.json
  src/courseware/course/new-sidebar/SidebarContextProvider.tsx
Labels: open-source-contribution

#1496 feat: Add plugin slots for progress page components
  src/course-home/progress-tab/ProgressHeader.jsx
  src/course-home/progress-tab/ProgressTab.jsx
  src/course-home/progress-tab/certificate-status/CertificateStatus.jsx
  src/course-home/progress-tab/course-completion/CompletionDonutChart.jsx
  src/course-home/progress-tab/credit-information/CreditInformation.jsx
  src/course-home/progress-tab/grades/course-grade/CourseGrade.jsx
  src/course-home/progress-tab/grades/course-grade/CourseGradeFooter.jsx
  src/course-home/progress-tab/grades/course-grade/CourseGradeHeader.jsx
  src/course-home/progress-tab/grades/course-grade/CurrentGradeTooltip.jsx
  src/course-home/progress-tab/grades/course-grade/GradeBar.jsx
  src/course-home/progress-tab/grades/course-grade/GradeRangeTooltip.jsx
  src/course-home/progress-tab/grades/detailed-grades/DetailedGrades.jsx
  src/course-home/progress-tab/grades/detailed-grades/DetailedGradesTable.jsx
  src/course-home/progress-tab/grades/detailed-grades/SubsectionTitleCell.jsx
  src/course-home/progress-tab/grades/grade-summary/AssignmentTypeCell.jsx
  src/course-home/progress-tab/grades/grade-summary/DroppableAssignmentFootnote.jsx
  src/course-home/progress-tab/grades/grade-summary/GradeSummary.jsx
  src/course-home/progress-tab/grades/grade-summary/GradeSummaryHeader.jsx
  src/course-home/progress-tab/grades/grade-summary/GradeSummaryTable.jsx
  src/course-home/progress-tab/grades/grade-summary/GradeSummaryTableFooter.jsx
  src/course-home/progress-tab/related-links/RelatedLinks.jsx
  src/data/hooks.ts
  src/index.jsx
  src/plugin-slots/ProgressTabCertificateStatusMainBodySlot/README.md
  src/plugin-slots/ProgressTabCertificateStatusMainBodySlot/images/progress_tab_certificate_status_slot.png
  src/plugin-slots/ProgressTabCertificateStatusMainBodySlot/index.jsx
  src/plugin-slots/ProgressTabCertificateStatusSidePanelSlot/README.md
  src/plugin-slots/ProgressTabCertificateStatusSidePanelSlot/images/progress_tab_certificate_status_slot.png
  src/plugin-slots/ProgressTabCertificateStatusSidePanelSlot/index.jsx
  src/plugin-slots/ProgressTabCourseGradeSlot/README.md
  src/plugin-slots/ProgressTabCourseGradeSlot/images/progress_tab_course_grade_slot.png
  src/plugin-slots/ProgressTabCourseGradeSlot/index.jsx
  src/plugin-slots/ProgressTabGradeBreakdownSlot/README.md
  src/plugin-slots/ProgressTabGradeBreakdownSlot/images/progress_tab_grade_breakdown_slot.png
  src/plugin-slots/ProgressTabGradeBreakdownSlot/index.jsx
  src/plugin-slots/ProgressTabRelatedLinksSlot/README.md
  src/plugin-slots/ProgressTabRelatedLinksSlot/images/progress_tab_related_links_slot.png
  src/plugin-slots/ProgressTabRelatedLinksSlot/index.jsx
  src/store.ts
Labels: open-source-contribution, core contributor

#1575 Update catalog-info file for release data
  catalog-info.yaml
  openedx.yaml
Labels: open-source-contribution, core contributor, waiting for eng review
