Repository openedx/frontend-app-learning, pull requests merged in 2025-04, with the labels that each got.

#1663 feat: upgrade to react 18
  package-lock.json
  package.json
  src/__snapshots__/index.test.jsx.snap
  src/course-home/courseware-search/hooks.test.jsx
  src/courseware/CoursewareContainer.test.jsx
  src/courseware/course/Course.test.jsx
  src/courseware/course/content-tools/calculator/Calculator.jsx
  src/courseware/course/sequence/Unit/hooks/useExamAccess.test.jsx
  src/courseware/course/sequence/sequence-navigation/SequenceNavigationTabs.test.jsx
  src/index.jsx
  src/index.test.jsx
  src/setupTest.js
  src/tests/MockedPluginSlot.test.jsx
Labels: create-sandbox

#1621 chore: remove 'patch-package' and its unused frontend-build patch
  package-lock.json
  package.json
  patches/@openedx+frontend-build+13.0.30.patch
Labels: open-source-contribution, waiting on author, core contributor, waiting for eng review

#1677 chore(deps): update dependency @openedx/frontend-build
  package-lock.json
  package.json
Labels: open-source-contribution

#1685 feat: standardize slot ids
  package-lock.json
  package.json
  src/course-home/outline-tab/OutlineTab.jsx
  src/course-home/outline-tab/OutlineTab.test.jsx
  src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.test.tsx
  src/courseware/course/new-sidebar/sidebars/discussions-notifications/notifications/NotificationsWidget.tsx
  src/courseware/course/sequence/Unit/ContentIFrame.jsx
  src/courseware/course/sequence/Unit/ContentIFrame.test.jsx
  src/courseware/course/sequence/Unit/UnitSuspense.jsx
  src/courseware/course/sequence/Unit/UnitSuspense.test.jsx
  src/courseware/course/sequence/Unit/index.test.jsx
  src/courseware/course/sidebar/sidebars/notifications/NotificationTray.jsx
  src/courseware/course/sidebar/sidebars/notifications/NotificationTray.test.jsx
  src/plugin-slots/ContentIFrameLoaderSlot/README.md
  src/plugin-slots/ContentIFrameLoaderSlot/index.tsx
  src/plugin-slots/CourseBreadcrumbsSlot/README.md
  src/plugin-slots/CourseBreadcrumbsSlot/index.tsx
  src/plugin-slots/CourseHomeSectionOutlineSlot/README.md
  src/plugin-slots/CourseHomeSectionOutlineSlot/index.tsx
  src/plugin-slots/CourseOutlineMobileSidebarTriggerSlot/README.md
  src/plugin-slots/CourseOutlineMobileSidebarTriggerSlot/index.tsx
  src/plugin-slots/CourseOutlineSidebarSlot/README.md
  src/plugin-slots/CourseOutlineSidebarSlot/index.tsx
  src/plugin-slots/CourseOutlineSidebarTriggerSlot/README.md
  src/plugin-slots/CourseOutlineSidebarTriggerSlot/index.tsx
  src/plugin-slots/CourseOutlineTabNotificationsSlot/README.md
  src/plugin-slots/CourseOutlineTabNotificationsSlot/index.tsx
  src/plugin-slots/CourseRecommendationsSlot/README.md
  src/plugin-slots/CourseRecommendationsSlot/index.jsx
  src/plugin-slots/GatedUnitContentMessageSlot/README.md
  src/plugin-slots/GatedUnitContentMessageSlot/index.tsx
  src/plugin-slots/HeaderSlot/README.md
  src/plugin-slots/HeaderSlot/index.jsx
  src/plugin-slots/NextUnitTopNavTriggerSlot/README.md
  src/plugin-slots/NextUnitTopNavTriggerSlot/index.tsx
  src/plugin-slots/NotificationTraySlot/README.md
  src/plugin-slots/NotificationTraySlot/index.tsx
  src/plugin-slots/NotificationWidgetSlot/README.md
  src/plugin-slots/NotificationWidgetSlot/index.tsx
  src/plugin-slots/NotificationsDiscussionsSidebarSlot/README.md
  src/plugin-slots/NotificationsDiscussionsSidebarSlot/index.tsx
  src/plugin-slots/NotificationsDiscussionsSidebarTriggerSlot/README.md
  src/plugin-slots/NotificationsDiscussionsSidebarTriggerSlot/index.tsx
  src/plugin-slots/ProgressCertificateStatusSlot/README.md
  src/plugin-slots/ProgressCertificateStatusSlot/index.jsx
  src/plugin-slots/ProgressTabCertificateStatusMainBodySlot/README.md
  src/plugin-slots/ProgressTabCertificateStatusMainBodySlot/index.jsx
  src/plugin-slots/ProgressTabCertificateStatusSidePanelSlot/README.md
  src/plugin-slots/ProgressTabCertificateStatusSidePanelSlot/index.jsx
  src/plugin-slots/ProgressTabCourseGradeSlot/README.md
  src/plugin-slots/ProgressTabCourseGradeSlot/index.jsx
  src/plugin-slots/ProgressTabGradeBreakdownSlot/README.md
  src/plugin-slots/ProgressTabGradeBreakdownSlot/index.jsx
  src/plugin-slots/ProgressTabRelatedLinksSlot/README.md
  src/plugin-slots/ProgressTabRelatedLinksSlot/index.jsx
  src/plugin-slots/README.md
  src/plugin-slots/SequenceContainerSlot/README.md
  src/plugin-slots/SequenceContainerSlot/index.jsx
  src/plugin-slots/UnitTitleSlot/README.md
  src/plugin-slots/UnitTitleSlot/index.jsx
Labels: create-sandbox

#1687 feat: replace edX® certificate icons
  src/courseware/course/course-exit/CourseCelebration.jsx
  src/courseware/course/course-exit/ProgramCompletion.jsx
  src/courseware/course/sequence/lock-paywall/LockPaywall.jsx
  src/generic/assets/edX_certificate.png
  src/generic/assets/edX_locked_certificate.png
  src/generic/assets/openedx_certificate.png
  src/generic/assets/openedx_locked_certificate.png
Labels: open-source-contribution
