Repository openedx/frontend-app-learning, pull requests merged in 2025-05, with the labels that each got.

#1693 feat(teak): update certificate icons
  src/courseware/course/course-exit/CourseCelebration.jsx
  src/courseware/course/course-exit/ProgramCompletion.jsx
  src/courseware/course/sequence/lock-paywall/LockPaywall.jsx
  src/generic/assets/edX_certificate.png
  src/generic/assets/edX_locked_certificate.png
  src/generic/assets/openedx_certificate.png
  src/generic/assets/openedx_locked_certificate.png
Labels: open-source-contribution

#1676 Remove unused <ShareButton>, replace query-string with newer APIs
  package-lock.json
  package.json
  src/courseware/RedirectPage.test.jsx
  src/courseware/RedirectPage.tsx
  src/courseware/course/sequence/Unit/urls.js
  src/courseware/course/sequence/Unit/urls.test.js
  src/courseware/course/sequence/Unit/urls.test.ts
  src/courseware/course/sequence/Unit/urls.ts
  src/courseware/course/share/ShareButton.jsx
  src/courseware/course/share/messages.ts
Labels: open-source-contribution, core contributor, waiting for eng review

#1588 feat: support design tokens and paragon 23
  .env
  .env.development
  package-lock.json
  package.json
  src/course-home/courseware-search/courseware-search.scss
  src/course-home/outline-tab/widgets/FlagButton.scss
  src/course-home/outline-tab/widgets/ProctoringInfoPanel.scss
  src/course-home/progress-tab/course-completion/CompletionDonutChart.scss
  src/course-home/progress-tab/grades/course-grade/GradeBar.scss
  src/course-tabs/course-tabs-navigation.scss
  src/courseware/course/celebration/CelebrationModal.scss
  src/courseware/course/content-tools/calculator/Calculator.jsx
  src/courseware/course/content-tools/calculator/calculator.scss
  src/courseware/course/content-tools/contentTools.scss
  src/courseware/course/sequence/Unit/ContentIFrame.jsx
  src/courseware/course/sequence/Unit/ContentIFrame.test.jsx
  src/courseware/course/sequence/lock-paywall/LockPaywall.scss
  src/courseware/course/sidebar/common/SidebarBase.scss
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.scss
  src/courseware/course/sidebar/sidebars/discussions/Discussions.scss
  src/generic/upsell-bullets/UpsellBullets.scss
  src/index.scss
  src/instructor-toolbar/masquerade-widget/MasqueradeUserNameInput.tsx
  src/product-tours/newUserCourseHomeTour/NewUserCourseHomeTourModal.scss
Labels: open-source-contribution, core contributor, create-sandbox

#1679 fix: sidebar not showing sections on pending courses
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.jsx
Labels: open-source-contribution, waiting for eng review, product review complete, create-sandbox, mao-onboarding

#1716 feat: move sequence navigation to plugin slot
  src/courseware/course/sequence/Sequence.jsx
  src/plugin-slots/README.md
  src/plugin-slots/SequenceNavigationSlot/README.md
  src/plugin-slots/SequenceNavigationSlot/index.jsx
  src/plugin-slots/SequenceNavigationSlot/screenshot_custom.png
  src/plugin-slots/SequenceNavigationSlot/screenshot_default.png
Labels: open-source-contribution

#1721 chore: add workflow to pull release testing issues into the BTR board
  .github/add-issue-to-btr-project.yml
Labels: open-source-contribution, core contributor
