Repository openedx/frontend-app-learning, pull requests merged in 2025-03, with the labels that each got.

#1583 feat: close sidebar on mobile after selecting a unit
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarUnit.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/hooks.jsx
Labels: open-source-contribution, waiting on author, core contributor, product review complete

#1622 Remove "husky"
  .husky/pre-commit
  package-lock.json
  package.json
Labels: open-source-contribution

#1620 Updated Courseware Search screen reader a11y
  src/course-home/courseware-search/CoursewareSearch.jsx
  src/course-home/courseware-search/CoursewareSearch.test.jsx
Labels: open-source-contribution

#1636 fix: right sidebar icon behavior
  src/courseware/course/new-sidebar/sidebars/discussions-notifications/DiscussionsNotificationsTrigger.tsx
Labels: open-source-contribution, product review, core contributor

#1640 fix: use sentence casing
  src/course-home/progress-tab/ProgressTab.test.jsx
  src/course-home/progress-tab/grades/messages.ts
  src/course-home/progress-tab/related-links/messages.ts
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/messages.ts
Labels: open-source-contribution

#1632 feat: add section outline plugin
  src/course-home/outline-tab/OutlineTab.jsx
  src/course-home/outline-tab/OutlineTab.test.jsx
  src/course-home/outline-tab/Section.jsx
  src/course-home/outline-tab/SequenceLink.jsx
  src/course-home/outline-tab/messages.ts
  src/course-home/outline-tab/section-outline/HiddenSequenceLink.tsx
  src/course-home/outline-tab/section-outline/Section.tsx
  src/course-home/outline-tab/section-outline/SectionTitle.tsx
  src/course-home/outline-tab/section-outline/SequenceDueDate.tsx
  src/course-home/outline-tab/section-outline/SequenceLink.tsx
  src/course-home/outline-tab/section-outline/SequenceTitle.tsx
  src/plugin-slots/CourseHomeSectionOutlineSlot/README.md
  src/plugin-slots/CourseHomeSectionOutlineSlot/index.tsx
  src/plugin-slots/CourseHomeSectionOutlineSlot/screenshot_custom.png
  src/plugin-slots/CourseHomeSectionOutlineSlot/screenshot_default.png
Labels: open-source-contribution, core contributor

#1643 feat: update unit title plugin
  src/courseware/course/sequence/Unit/__snapshots__/index.test.jsx.snap
  src/courseware/course/sequence/Unit/index.jsx
  src/courseware/course/sequence/Unit/index.test.jsx
  src/plugin-slots/UnitTitleSlot/README.md
  src/plugin-slots/UnitTitleSlot/images/post_unit_title.png
  src/plugin-slots/UnitTitleSlot/images/screenshot_custom.png
  src/plugin-slots/UnitTitleSlot/index.jsx
Labels: open-source-contribution

#1653 fix: button hover background color
  src/courseware/course/sequence/sequence-navigation/generic/NextButton.jsx
  src/courseware/course/sequence/sequence-navigation/generic/PreviousButton.jsx
Labels: open-source-contribution
