Repository openedx/frontend-app-learning, pull requests merged in 2025-02, with the labels that each got.

#1585 fix: Ugly appearance of the Start/Resume Course button at the top of the course outline
  src/index.scss
Labels: open-source-contribution, waiting for eng review

#1591 feat: update version of frontend-lib-special-exams library from 3.2.0 to 3.2.1
  package-lock.json
Labels: open-source-contribution

#1586 fix: update outline sidebar hooks for plugins
  src/courseware/course/sidebar/sidebars/course-outline/CourseOutlineTray.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSection.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSection.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSequence.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarSequence.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarUnit.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/SidebarUnit.test.jsx
  src/courseware/course/sidebar/sidebars/course-outline/components/UnitLinkWrapper.tsx
  src/courseware/course/sidebar/sidebars/course-outline/hooks.jsx
Labels: open-source-contribution, waiting on author, core contributor

#1608 fix: remove husky internal files that should never have been committed
  .husky/_/.gitignore
  .husky/_/husky.sh
  .husky/pre-commit
  package.json
Labels: open-source-contribution
